dbt_gcp_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: andrew-learns-gcp-403022 # name of the project in BigQuery
      dataset: bigquery-public-data.crypto_bitcoin # your dataset for development (usually your name)
      location: EU
      threads: 4
      keyfile: projects/1082339105905/secrets/andrew-learns-gcp-key
      timeout_seconds: 300
      priority: interactive
      retries: 1

    prod: # your production environment
      type: bigquery
      method: service-account
      project: andrew-learns-gcp-403022 # name of the project in BigQuery
      dataset: bigquery-public-data.crypto_bitcoin # your dataset for production
      location: EU
      threads: 4
      keyfile: projects/1082339105905/secrets/andrew-learns-gcp-key
      timeout_seconds: 300
      priority: interactive
      retries: 1
