dbt_gcp_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: andrew-learns-gcp # name of the project in BigQuery
      dataset: dbt_andrew # your dataset for development (usually your name)
      threads: 4
      keyfile: /secrets/andrew-learns-gcp-key
      timeout_seconds: 300
      priority: interactive
      retries: 1

    prod: # your production environment
      type: bigquery
      method: service-account
      project: quickstart # name of the project in BigQuery
      dataset: dbt_production # your dataset for production
      threads: 4
      keyfile: /secrets/andrew-learns-gcp-key
      timeout_seconds: 300
      priority: interactive
      retries: 1
